package com.krishihr.app

/**
 * ╔══════════════════════════════════════════════════════════════════════╗
 * ║                       Android_main.kt                               ║
 * ║           Single Central Config — RiskcareHRMS Android              ║
 * ║                                                                      ║
 * ║  ⚠️  THIS IS THE ONLY FILE YOU NEED TO EDIT FOR WHITE-LABELLING     ║
 * ║  Change brand name, colors, URL, logo ref — all in one place.       ║
 * ║  No other file should contain any of these hardcoded values.        ║
 * ╚══════════════════════════════════════════════════════════════════════╝
 */
object AndroidMain {

    // ══════════════════════════════════════════════════════════════════
    // 1. BRAND & IDENTITY
    //    Everything visible to the user — name, company, logo, footer
    // ══════════════════════════════════════════════════════════════════

    /** Short app name shown in notifications, dialogs, permission screens */
    const val APP_NAME = "RiskcareHRMS"

    /** Full legal company name shown on payslips and PDF headers */
    const val COMPANY_NAME = "Risk Care Insurance Broking Pvt. Ltd."

    /** Short company name used in logo alt-text and headers */
    const val COMPANY_SHORT_NAME = "Risk Care"

    /** Tagline shown on splash / login screen */
    const val APP_TAGLINE = "Smart HR for Insurance"

    /** Footer text on generated PDFs/HTML reports */
    const val PDF_FOOTER_PREFIX = "Generated by RiskcareHRMS"

    /** Folder name under Downloads where PDFs are saved */
    const val DOWNLOADS_FOLDER = "RiskcareHRMS"

    /** Toast message shown after PDF is saved */
    const val PDF_SAVED_TOAST = "✅ PDF saved to Downloads/RiskcareHRMS"

    // ── Logo ──────────────────────────────────────────────────────────
    // Replace ic_logo.png in res/drawable/ with your logo file.
    // Reference it in XML as @drawable/ic_logo
    // The drawable name is kept as ic_logo so no XML changes are needed.
    const val LOGO_DRAWABLE = "ic_logo"   // just the name, used for docs/comments


    // ══════════════════════════════════════════════════════════════════
    // 2. BRAND COLORS
    //    These are documented here for reference.
    //    Actual color values live in res/values/colors.xml
    //    Change primary / primary_dark / primary_light there to rebrand.
    // ══════════════════════════════════════════════════════════════════
    //
    //  primary            →  #1A3C6E  (deep navy blue  — Risk Care brand)
    //  primary_dark       →  #0F2548
    //  primary_light      →  #2E5FA3
    //  primary_ultra_light→  #E8EEF8
    //  accent_orange      →  #E65100  (CTA buttons)
    //
    //  To change theme colour: edit res/values/colors.xml only.


    // ══════════════════════════════════════════════════════════════════
    // 3. NETWORK — Backend URL
    // ══════════════════════════════════════════════════════════════════

    /** Base URL for ALL Retrofit API calls. Must end with /api/ */
    const val BASE_URL = "https://riskcarehrms.onrender.com/api/"

    // OkHttp timeouts (seconds)
    const val TIMEOUT_CONNECT_SEC = 30L
    const val TIMEOUT_READ_SEC    = 60L    // longer for Render cold-start
    const val TIMEOUT_WRITE_SEC   = 120L   // longer for image/PDF uploads


    // ══════════════════════════════════════════════════════════════════
    // 4. DEEP LINK SCHEME
    //    Must also match AndroidManifest.xml <data android:scheme="..."/>
    // ══════════════════════════════════════════════════════════════════

    /** URI scheme for push-notification deep links e.g. riskcare://approvals?tab=1 */
    const val DEEP_LINK_SCHEME = "riskcare"


    // ══════════════════════════════════════════════════════════════════
    // 5. SHARED PREFERENCES — names & keys
    // ══════════════════════════════════════════════════════════════════

    const val PREFS_MAIN        = "RiskcareHRMS_Prefs"
    const val PREFS_ATT_CACHE   = "RiskcareHRMS_AttCache"
    const val PREFS_LEAVE_CACHE = "RiskcareHRMS_LeaveCache"
    const val PREFS_DASH_CACHE  = "RiskcareHRMS_DashCache"
    const val PREFS_TRACK       = "RiskcareHRMS_TrackPrefs"

    const val KEY_TOKEN         = "auth_token"
    const val KEY_EMPLOYEE      = "employee_data"
    const val KEY_IS_LOGGED_IN  = "is_logged_in"
    const val KEY_DEVICE_ID     = "device_id"


    // ══════════════════════════════════════════════════════════════════
    // 6. FILE NAMES  (stored in context.filesDir)
    // ══════════════════════════════════════════════════════════════════

    const val FILE_PROFILE_PHOTO = "profile_photo.b64"
    // Employee photo pattern: "emp_photo_$id.b64" — built at runtime


    // ══════════════════════════════════════════════════════════════════
    // 7. NOTIFICATION / FOREGROUND SERVICE
    // ══════════════════════════════════════════════════════════════════

    const val NOTIF_CHANNEL_ID   = "riskcare_tracking_channel"
    const val NOTIF_CHANNEL_NAME = "Location Tracking"
    const val NOTIF_ID           = 9001
    const val NOTIF_TITLE        = "RiskcareHRMS — Tracking Active"
    const val NOTIF_TEXT         = "Location recorded every 30 seconds"

    const val ACTION_LOCATION_UPDATE = "com.krishihr.app.LOCATION_UPDATE"
    const val ACTION_STOP_TRACKING   = "com.krishihr.app.STOP_TRACKING"


    // ══════════════════════════════════════════════════════════════════
    // 8. LOCATION TRACKING — intervals & thresholds
    // ══════════════════════════════════════════════════════════════════

    const val TRACK_INTERVAL_MOVING_MS      = 30_000L
    const val TRACK_INTERVAL_STATIONARY_MS  = 60_000L
    const val TRACK_STATIONARY_THRESHOLD_M  = 50f
    const val TRACK_LOCATION_CACHE_MS       = 60_000L
    const val TRACK_WAKELOCK_TIMEOUT_MS     = 60_000L
    const val MOVEMENT_LIVE_REFRESH_MS      = 30_000L


    // ══════════════════════════════════════════════════════════════════
    // 9. GEOFENCE & PUNCH-IN
    // ══════════════════════════════════════════════════════════════════

    const val GEOFENCE_MAX_RADIUS_M         = 50000
    const val GEOFENCE_VALIDATE_COOLDOWN_MS = 60_000L
    const val GEOFENCE_LOCATION_REQUEST_MS  = 5000L
    const val PUNCH_TOAST_DELAY_MS          = 3000L
    const val PUNCH_RETRY_DELAY_MS          = 15_000L


    // ══════════════════════════════════════════════════════════════════
    // 10. SPLASH SCREEN — health ping & delays (milliseconds)
    // ══════════════════════════════════════════════════════════════════

    const val HEALTH_PING_TIMEOUT_SEC   = 8L
    const val HEALTH_PING_MAX_ATTEMPTS  = 18
    const val HEALTH_PING_INTERVAL_MS   = 5000L

    const val SPLASH_INITIAL_DELAY_MS   = 600L
    const val SPLASH_SLOW_MSG_DELAY_MS  = 800L
    const val SPLASH_CONNECTED_DELAY_MS = 300L
    const val SPLASH_WORKSPACE_DELAY_MS = 300L


    // ══════════════════════════════════════════════════════════════════
    // 11. WAKELOCK TAGS
    // ══════════════════════════════════════════════════════════════════

    const val WAKELOCK_TAG_GPS      = "RiskcareHRMS::GPS"
    const val WAKELOCK_TAG_RECEIVER = "RiskcareHRMS::LayerOneReceiver"


    // ══════════════════════════════════════════════════════════════════
    // 12. SPECIAL EMPLOYEE CODES
    // ══════════════════════════════════════════════════════════════════

    /** Employee code that can see ALL movement data regardless of role */
    const val SEE_ALL_MOVEMENT_CODE = "RC001"


    // ══════════════════════════════════════════════════════════════════
    // 13. NOTICE PERIOD DAYS  (must match backend separationController.js)
    // ══════════════════════════════════════════════════════════════════

    const val NOTICE_DAYS_SENIOR  = 90   // SUPER_ADMIN, ADMIN, HR, ACCOUNTS
    const val NOTICE_DAYS_MANAGER = 45   // MANAGER
    const val NOTICE_DAYS_DEFAULT = 30   // TL, EMPLOYEE, unknown


    // ══════════════════════════════════════════════════════════════════
    // 14. GK QUIZ
    // ══════════════════════════════════════════════════════════════════

    const val GK_QUESTION_TIMER_MS = 30_000L


    // ══════════════════════════════════════════════════════════════════
    // 15. USER-FACING STRINGS (auto-use APP_NAME — don't hardcode)
    // ══════════════════════════════════════════════════════════════════

    val PERMISSION_LOCATION_RATIONALE get() =
        "$APP_NAME needs your location to:\n\n" +
                "• Record your punch-in/out location\n" +
                "• Verify you are within the office geofence\n" +
                "• Track field visits (OD)\n\n" +
                "Location is only recorded during work hours."

    val PERMISSION_BACKGROUND_SETTINGS_HINT get() =
        "To enable full tracking: Settings → Apps → $APP_NAME → Permissions → Location → Allow all the time"

    fun getBatteryOptSteps(brand: String): Pair<String, String> = when {
        brand.contains("xiaomi") || brand.contains("redmi") || brand.contains("poco") ->
            "📍 Enable AutoStart for Tracking" to
                    "To ensure location tracking works when app is closed:\n\n" +
                    "1. Open Phone Settings\n2. Go to Apps → $APP_NAME → Battery Saver\n" +
                    "3. Select No restrictions\n4. Go back → AutoStart → Enable ✅\n\n" +
                    "Without this, tracking stops after closing the app."
        brand.contains("oppo") || brand.contains("realme") ->
            "📍 Allow Background Activity" to
                    "To ensure location tracking works when app is closed:\n\n" +
                    "1. Open Phone Settings\n2. Go to Battery → App Battery Management\n" +
                    "3. Find $APP_NAME → Allow background activity ✅\n\n" +
                    "Without this, tracking stops after closing the app."
        brand.contains("oneplus") ->
            "📍 Disable Deep Optimization" to
                    "To ensure location tracking works when app is closed:\n\n" +
                    "1. Open Phone Settings\n2. Go to Battery → Battery Optimization\n" +
                    "3. Find $APP_NAME → Don't optimize ✅\n\n" +
                    "Without this, tracking stops after closing the app."
        brand.contains("vivo") ->
            "📍 Enable Background Location" to
                    "To ensure location tracking works when app is closed:\n\n" +
                    "1. Open iManager app\n2. Go to App Manager → $APP_NAME\n" +
                    "3. Enable Background Power Consumption ✅\n\n" +
                    "Without this, tracking stops after closing the app."
        brand.contains("huawei") || brand.contains("honor") ->
            "📍 Enable AutoLaunch" to
                    "To ensure location tracking works when app is closed:\n\n" +
                    "1. Open Phone Settings\n2. Go to Apps → $APP_NAME → Battery\n" +
                    "3. Enable Auto Launch & Run in background ✅\n\n" +
                    "Without this, tracking stops after closing the app."
        brand.contains("samsung") ->
            "📍 Remove Battery Restriction" to
                    "To ensure location tracking works when app is closed:\n\n" +
                    "1. Open Phone Settings\n2. Go to Apps → $APP_NAME → Battery\n" +
                    "3. Select Unrestricted ✅\n\n" +
                    "Without this, Samsung stops tracking after ~10 minutes."
        else ->
            "📍 Allow Background Location" to
                    "To ensure location tracking works when app is closed:\n\n" +
                    "1. Open Phone Settings\n2. Go to Apps → $APP_NAME → Battery\n" +
                    "3. Select Unrestricted or No restrictions ✅\n\n" +
                    "This ensures your attendance is tracked correctly."
    }
}
