package com.krishihr.app

/**
 * ╔══════════════════════════════════════════════════════════════════════╗
 * ║                       Android_main.kt                               ║
 * ║           Single Central Config — RiskcareHRMS Android              ║
 * ║                                                                      ║
 * ║  ⚠️  THIS IS THE ONLY FILE YOU NEED TO EDIT FOR WHITE-LABELLING     ║
 * ║  Change brand name, colors, URL, logo ref — all in one place.       ║
 * ║  No other file should contain any of these hardcoded values.        ║
 * ║                                                                      ║
 * ║  SOURCE OF TRUTH: backend/Main_file.js (RiskcareHRMS repo)          ║
 * ║  Keep this file in sync with that file when backend values change.  ║
 * ╚══════════════════════════════════════════════════════════════════════╝
 */
object AndroidMain {

    // ══════════════════════════════════════════════════════════════════
    // 1. BRAND & IDENTITY
    //    Synced from: backend/Main_file.js → clientName / companyFullName
    // ══════════════════════════════════════════════════════════════════

    /** Short app name shown in notifications, dialogs, permission screens */
    const val APP_NAME = "RiskCareHR"

    /** Full legal company name shown on payslips and PDF headers */
    const val COMPANY_FULL_NAME = "Risk Care Insurance Broking Services Pvt. Ltd."

    /** Short company name used in logo alt-text and headers */
    const val COMPANY_SHORT_NAME = "Risk Care Insurance"

    /** tagline shown on splash / login screen */
    const val APP_TAGLINE = "Servicing All Risks"

    /** CIN for compliance/legal documents */
    const val COMPANY_CIN = "U51109MH2005PTC199431"

    /** Registered office address */
    const val COMPANY_OFFICE_ADDR =
        "708, 7th Floor, Hubtown Viva, Western Express Highway, " +
        "Shankarwadi, Jogeshwari (East), Mumbai - 400060"

    /** Corporate address (same as office for Riskcare) */
    const val COMPANY_CORPORATE_ADDR = COMPANY_OFFICE_ADDR

    /** Landline shown on formal documents */
    const val COMPANY_TEL = "+912261473232"

    /** Mobile / corporate contact */
    const val COMPANY_CORPORATE_TEL = "+919004028426"

    /** City — used in tax / regional logic */
    const val COMPANY_CITY = "Mumbai"

    /** Support / HR email shown on Form16 and official PDFs */
    const val COMPANY_EMAIL = "support@riskcare.co.in"

    /** Website shown on Form16 and official PDFs */
    const val COMPANY_WEBSITE = "riskcareinsure.com"

    /** Footer text on generated PDFs/HTML reports */
    const val PDF_FOOTER_PREFIX = "Generated by RiskCareHR"

    /** Folder name under Downloads where PDFs are saved */
    const val DOWNLOADS_FOLDER = "RiskCareHR"

    /** Toast message shown after PDF is saved */
    const val PDF_SAVED_TOAST = "✅ PDF saved to Downloads/RiskCareHR"

    // ── Logo ──────────────────────────────────────────────────────────
    // Replace ic_logo.png in res/drawable/ with the RiskCare logo.
    // Reference in XML as @drawable/ic_logo
    const val LOGO_DRAWABLE = "ic_logo"   // drawable resource name — used for docs/comments


    // ══════════════════════════════════════════════════════════════════
    // 2. BRAND COLORS
    //    Synced from: backend/Main_file.js → primaryColor / accentColor
    //
    //    Actual color values live in res/values/colors.xml
    //    Change primary / primary_dark / primary_light there to rebrand.
    //
    //  primary            →  #E8303A  (RiskCare brand red)
    //  primary_dark       →  #C0272D  (deep red — hover/dark states)
    //  primary_light      →  #FF5252  (light red — soft highlights)
    //  primary_ultra_light→  #FFEBEE  (pale red — card backgrounds)
    //  accent_cyan        →  #00AEEF  (RiskCare brand cyan — secondary)
    //  accent_navy        →  #1A2B5A  (RiskCare navy — text/icons)
    //
    //  To change theme colour: edit res/values/colors.xml only.
    //  These constants are documentation; they are not used in code.

    const val COLOR_PRIMARY             = "#E8303A"   // Brand red
    const val COLOR_PRIMARY_DARK        = "#C0272D"   // Deep red
    const val COLOR_PRIMARY_LIGHT       = "#FF5252"   // Light red
    const val COLOR_PRIMARY_ULTRA_LIGHT = "#FFEBEE"   // Pale red (card bg)
    const val COLOR_ACCENT_CYAN         = "#00AEEF"   // Brand cyan
    const val COLOR_ACCENT_NAVY         = "#1A2B5A"   // Brand navy
    const val COLOR_WHITE               = "#FFFFFF"
    const val COLOR_BACKGROUND          = "#F5F8FB"


    // ══════════════════════════════════════════════════════════════════
    // 3. NETWORK — Backend URL
    //    Synced from: backend/Main_file.js → backendUrl + apiBasePath
    // ══════════════════════════════════════════════════════════════════

    /** Base URL for ALL Retrofit API calls. Must end with /api/ */
    const val BASE_URL = "https://riskcarehrms.onrender.com/api/"

    /** OkHttp timeouts (seconds) */
    const val TIMEOUT_CONNECT_SEC = 30L
    const val TIMEOUT_READ_SEC    = 60L    // longer for Render cold-start
    const val TIMEOUT_WRITE_SEC   = 120L   // longer for image/PDF uploads


    // ══════════════════════════════════════════════════════════════════
    // 4. DEEP LINK SCHEME
    //    Must also match AndroidManifest.xml <data android:scheme="..."/>
    //    Synced from: backend/Main_file.js → appDeepLinkScheme
    // ══════════════════════════════════════════════════════════════════

    /** URI scheme for push-notification deep links e.g. riskcarehr://approvals?tab=1 */
    const val DEEP_LINK_SCHEME = "riskcarehr"


    // ══════════════════════════════════════════════════════════════════
    // 5. SHARED PREFERENCES — names & keys
    //    Synced from: backend/Main_file.js → localStoragePrefix
    // ══════════════════════════════════════════════════════════════════

    const val PREFS_MAIN        = "RiskCareHR_Prefs"
    const val PREFS_ATT_CACHE   = "RiskCareHR_AttCache"
    const val PREFS_LEAVE_CACHE = "RiskCareHR_LeaveCache"
    const val PREFS_DASH_CACHE  = "RiskCareHR_DashCache"
    const val PREFS_TRACK       = "RiskCareHR_TrackPrefs"

    const val KEY_TOKEN        = "auth_token"
    const val KEY_EMPLOYEE     = "employee_data"
    const val KEY_IS_LOGGED_IN = "is_logged_in"
    const val KEY_DEVICE_ID    = "device_id"


    // ══════════════════════════════════════════════════════════════════
    // 6. FILE NAMES  (stored in context.filesDir)
    // ══════════════════════════════════════════════════════════════════

    const val FILE_PROFILE_PHOTO = "profile_photo.b64"
    // Employee photo pattern: "emp_photo_$id.b64" — built at runtime


    // ══════════════════════════════════════════════════════════════════
    // 7. NOTIFICATION / FOREGROUND SERVICE
    // ══════════════════════════════════════════════════════════════════

    const val NOTIF_CHANNEL_ID   = "riskcarehr_tracking_channel"
    const val NOTIF_CHANNEL_NAME = "Location Tracking"
    const val NOTIF_ID           = 9001
    const val NOTIF_TITLE        = "RiskCareHR — Tracking Active"
    const val NOTIF_TEXT         = "Location recorded every 30 seconds"

    const val ACTION_LOCATION_UPDATE = "com.riskcare.app.LOCATION_UPDATE"
    const val ACTION_STOP_TRACKING   = "com.riskcare.app.STOP_TRACKING"


    // ══════════════════════════════════════════════════════════════════
    // 8. LOCATION TRACKING — intervals & thresholds
    // ══════════════════════════════════════════════════════════════════

    const val TRACK_INTERVAL_MOVING_MS      = 30_000L
    const val TRACK_INTERVAL_STATIONARY_MS  = 60_000L
    const val TRACK_STATIONARY_THRESHOLD_M  = 50f
    const val TRACK_LOCATION_CACHE_MS       = 60_000L
    const val TRACK_WAKELOCK_TIMEOUT_MS     = 60_000L
    const val MOVEMENT_LIVE_REFRESH_MS      = 30_000L


    // ══════════════════════════════════════════════════════════════════
    // 9. GEOFENCE & PUNCH-IN
    // ══════════════════════════════════════════════════════════════════

    const val GEOFENCE_MAX_RADIUS_M         = 50000
    const val GEOFENCE_VALIDATE_COOLDOWN_MS = 60_000L
    const val GEOFENCE_LOCATION_REQUEST_MS  = 5000L
    const val PUNCH_TOAST_DELAY_MS          = 3000L
    const val PUNCH_RETRY_DELAY_MS          = 15_000L


    // ══════════════════════════════════════════════════════════════════
    // 10. SPLASH SCREEN — health ping & delays (milliseconds)
    // ══════════════════════════════════════════════════════════════════

    const val HEALTH_PING_TIMEOUT_SEC   = 8L
    const val HEALTH_PING_MAX_ATTEMPTS  = 18
    const val HEALTH_PING_INTERVAL_MS   = 5000L

    const val SPLASH_INITIAL_DELAY_MS   = 600L
    const val SPLASH_SLOW_MSG_DELAY_MS  = 800L
    const val SPLASH_CONNECTED_DELAY_MS = 300L
    const val SPLASH_WORKSPACE_DELAY_MS = 300L


    // ══════════════════════════════════════════════════════════════════
    // 11. WAKELOCK TAGS
    // ══════════════════════════════════════════════════════════════════

    const val WAKELOCK_TAG_GPS      = "RiskCareHR::GPS"
    const val WAKELOCK_TAG_RECEIVER = "RiskCareHR::LayerOneReceiver"


    // ══════════════════════════════════════════════════════════════════
    // 12. SPECIAL EMPLOYEE CODES
    //     Synced from: backend/Main_file.js → cooEmployeeCode / mdEmployeeCode
    // ══════════════════════════════════════════════════════════════════

    /** COO / Super-admin who can see ALL movement data regardless of role */
    const val SEE_ALL_MOVEMENT_CODE    = "RC001"

    /** MD employee code */
    const val MD_EMPLOYEE_CODE         = "RC01"

    /** Accounts lead employee code */
    const val ACCOUNTS_EMPLOYEE_CODE   = "RC002"

    /** Prefix used when generating permanent employee codes */
    const val EMP_CODE_PREFIX          = "RC"

    /** Prefix used when generating contractual employee codes */
    const val EMP_CODE_PREFIX_CONTRACT = "CT"


    // ══════════════════════════════════════════════════════════════════
    // 13. NOTICE PERIOD DAYS
    //     Synced from: backend/Main_file.js → noticePeriodSeniorDays etc.
    // ══════════════════════════════════════════════════════════════════

    const val NOTICE_DAYS_SENIOR  = 90   // SUPER_ADMIN, ADMIN, HR, ACCOUNTS
    const val NOTICE_DAYS_MANAGER = 45   // MANAGER
    const val NOTICE_DAYS_DEFAULT = 30   // TL, EMPLOYEE, unknown


    // ══════════════════════════════════════════════════════════════════
    // 14. ATTENDANCE BUSINESS RULES
    //     Synced from: backend/Main_file.js → punchInCutoffHour etc.
    // ══════════════════════════════════════════════════════════════════

    const val PUNCH_IN_CUTOFF_HOUR    = 10
    const val PUNCH_IN_CUTOFF_MINUTE  = 30
    const val PUNCH_OUT_CUTOFF_HOUR   = 18
    const val PUNCH_OUT_CUTOFF_MINUTE = 30
    const val MISSING_PUNCH_OUT_HOUR  = 21

    /** OD tracking window — start as HHMM int (e.g. 930 = 09:30) */
    const val OD_TRACKING_WINDOW_START = 930
    const val OD_TRACKING_WINDOW_END   = 1830

    const val MOVEMENT_LOG_RETENTION_DAYS = 3
    const val COMPOFF_EXPIRY_DAYS         = 30


    // ══════════════════════════════════════════════════════════════════
    // 15. APP META
    //     Synced from: backend/Main_file.js → appVersion / timezone
    // ══════════════════════════════════════════════════════════════════

    const val APP_VERSION       = "1.0.0"
    const val TIMEZONE          = "Asia/Kolkata"
    const val CURRENCY          = "INR"
    const val CURRENCY_SYMBOL   = "₹"
    const val DATE_FORMAT       = "DD/MM/YYYY"
    const val DEFAULT_REGION    = "south_west"
    const val SECONDARY_REGION  = "north"


    // ══════════════════════════════════════════════════════════════════
    // 16. CHAT & FILE SHARING
    //     Synced from: backend/Main_file.js → chatFileMaxSizeMB
    // ══════════════════════════════════════════════════════════════════

    const val CHAT_FILE_MAX_SIZE_MB = 1024
    val CHAT_BLOCKED_EXTENSIONS = listOf(".exe", ".bat", ".sh", ".cmd", ".msi", ".ps1", ".vbs")


    // ══════════════════════════════════════════════════════════════════
    // 17. PERFORMANCE MANAGEMENT
    //     Synced from: backend/Main_file.js → performanceRatingScale etc.
    // ══════════════════════════════════════════════════════════════════

    const val PERFORMANCE_RATING_SCALE   = 5
    const val PERFORMANCE_DEFAULT_WEIGHT = 20

    val PERFORMANCE_FINAL_RATINGS = listOf(
        "Outstanding",
        "Exceeds Expectations",
        "Meets Expectations",
        "Needs Improvement",
        "Unsatisfactory"
    )


    // ══════════════════════════════════════════════════════════════════
    // 18. GK QUIZ
    // ══════════════════════════════════════════════════════════════════

    const val GK_QUESTION_TIMER_MS = 30_000L


    // ══════════════════════════════════════════════════════════════════
    // 20. GOOGLE MAPS API KEY
    //     Also referenced in AndroidManifest.xml meta-data.
    //     To rotate: update here AND in AndroidManifest.xml.
    // ══════════════════════════════════════════════════════════════════

    const val GOOGLE_MAPS_API_KEY = "AIzaSyDp21tx1U1OVaXIGv8E8Y94RmfnQl1pNbo"


    // ══════════════════════════════════════════════════════════════════
    // 21. CHAT ATTACHMENT DOWNLOAD FOLDER
    //     Folder under Downloads/ where chat attachments are saved.
    // ══════════════════════════════════════════════════════════════════

    const val CHAT_ATTACHMENTS_FOLDER = "$APP_NAME/Attachments"
    const val CHAT_FILE_SAVED_TOAST   = "✅ Saved: Downloads/$APP_NAME/Attachments"


    // ══════════════════════════════════════════════════════════════════
    // 22. PAYSLIP / FORM16 — Company address lines for PDF header
    //     Synced from: backend/Main_file.js → companyOfficeAddr
    // ══════════════════════════════════════════════════════════════════

    /** Address line 1 shown on payslip PDF header */
    const val PAYSLIP_ADDR_LINE1 =
        "Office Address: 708, 7th Floor, Hubtown Viva, Western Express Highway,"

    /** Address line 2 shown on payslip PDF header */
    const val PAYSLIP_ADDR_LINE2 =
        "Shankarwadi, Jogeshwari (East), Mumbai \u2013 400060."

    /** Single-line full address for Form16 HTML */
    const val FORM16_ADDR_FULL =
        "708, 7th Floor, Hubtown Viva, Western Express Highway, " +
        "Shankarwadi, Jogeshwari (East), Mumbai \u2013 400060"

    /** Contact line shown below address on Form16 */
    const val FORM16_CONTACT_LINE = "$COMPANY_EMAIL | $COMPANY_WEBSITE"

    /**
     * Logo embedded as base64 data URI in Form16 PDF HTML.
     * Replace with new client's logo by converting their logo PNG to base64:
     *   python3 -c "import base64; print('data:image/png;base64,' + base64.b64encode(open('logo.png','rb').read()).decode())"
     */
    const val FORM16_LOGO_DATA_URI = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIgAAABMCAYAAAC2w//wAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAABc+SURBVHhe7V0JdBRV1gZBRYVBZV9lFxhQkOFXgSCQsA2OgCiICIisivzjIDvDpqKOjgjyixtn3BBEBwghQAJh3wMSZJN937o7na27s9Srqu8/36vel0BIiMT0Pec73elX71XVre/de99791VKICxhyUVK+P8QlrB4S5ggYclVwgQJS65yfYIoAkhJA66YgUum4oHLJuCqBUizAarqr5EbkhwNsOTouJSp4cJthitZGtKEDs3/ooNIaIJkZUNP2Alt6jyIvmMhIl+BiBhUPPDUYIioYVAHTYL23pfQk44Cuu6voaBCYmww5+DNQzZ03pGKRzda0XiDFY0Tbg802WDFX7akoM+eNHxwwoFjNhW53VlwgmTYoU74N0TTv0HUjjLwUGeI2sUE8l6jIGpFQtTpAtHsb9Dmfic7TW6Somh4/UAGKq2x4I5VZpSIMaMEP29HxJhxZ6wZTROSEXM19H0FEsTugPrqLIhqTxmKCkNCqR0Jdc5/ADW4YbarOgbvT8cdtzMpQqBMtAk/XMyCCGJKfAmSo0CdPh+iapgcgYiCUr8r9JiNPiqjUK/vHHegdBEkhwu11lqw2aIEuBsfgui7DhhuJUA5YRAKSdK4B/TkVG+1YV+aQNkiTA6Clm/wvnTY/MyIhyBChTr7Cyh1AhUThheqd4D24xq32qjOyYdtt3e8cYOovS4ZJ+y+ozYPQRiYDp5iBGb+SgnDgzpdoI77ENCMWCRD1dFtZ2qAsosi7ooxI+aab8DqIYglBerTr4UJcgNQh0wFsnOk2i5maXhic0qAsoskVprw6dksL3p4E8RkhdptJEQt55A2jJBQB00GMo2exomn//kDEWTOGYcXPcIEuSn4ECQrTJAw/BAmSBClhOFBmCBBlBKGB2GCBFFKsUXNTlCqtIeoHAGlylPyu/rCm0CmEe2Hg9TiCC7U1esK5fF+UMe8A239DsBsNUjhyATsmcYMWdiCFD/IRbnuI6Et/C905oVcZ5k/TJDigjqdodTsCDFkMnD+SgAx0oUmp6F/SRM4lKHiarYmD6GLeTxMkEICcy9c8C+7EXAdSdYPUnYdcCFOHTUDEMKtkkxVx75UgaFJGbifC1orTCgRbULJFSbcvcKExhutmHXMjibrrYHKLoooFILUjoSo1QlKACI9iUf+4O8RA6H+3w9Q5/8Adeg/5aJYwHGhUDsKas8xUOcvkvVFx5dDnysYeOzw6UZ6pVPsQsf4wzZUWWMJvRAXY0bJlWaUDFVe1HDLCVKjE8TTr0Id/Q7U195yQ7z2NsTgSVDa9IdSuY0cGfjUqxkJtd+b7kvRv14OUaldYPuhUCsS2tRPjMBRB9SBE2WbAceFQtuXoB855T6/Q9URsTUFd/or8I+OW06QShHQvo32OYGP0Gmn26C+swBKkx6eeiRI37Ey5YDQ/7Ps5gjiFPWlGycILZs2+wt33UxNx6j96SgRYwpU4B8dhUKQb1a4m9RT02VyjZ5ug253GASQXVyFtnydkXtC8JyP94c6ZR7UKXOh9v0HRI2Oge2HQn4IUr2DEZQ6Jd6cg8pxyYHKKw4obIKoL46DaPk8ROt+EK1fgDpsGnRuoaAIAXXwZCguIriShEPEKooLtaOc36M8yU03S5BaUVD7/N1nxDIkidYjiPLyC9mmJfD3vEK247JuBdCeNwqbIFq3ET7tKVWfgjr+X57yJWugVGxrlNfrCtGyD0TL5yAedmbT83d+NvwrlNZ9oEYNg+g8FKJdfygte0M0edo4JjeCkETNehntEq5MfZZVfQra0rXueooO1Min9Si9yowacRa0jEtGxEYrOmxOQZsEKxrFJeNuv2NLrTKjZpwF9ddZUHGNBXetMuPhtRZZ77EEq4eoMWbcywz0OKOsw8YUPBZvRYXcAuibwe9OEAanvUa7y/W1W6FUaGMc02Gw4ZJS0qDN/NRInOaDbNEb2s9xMnaRPZ2gq0q3Q/v4W7fVCUYQWhnRbRj0/UehW9Ogn74AddRMT1JUlfbQDxxz1zucoaJkdBDF3ShWmtF1ZxqS0oXMcmfOGW0T0zwvZ2mYc8KBOvHJ7odaYU0yYq/mwJSjYf6pTEw4aMO1bB2qDuxKVeRwmsc2TbBi4dlMXMvRZBnbZPtrr2Wj0/bUghtF/a4EqRMFpWpbaN+vdJerny2BUrGdcUzkEE+9fy2EqNweomZHuXlLqoTE4DR3ht34FCq0FQmGpQhCEJIxp24U9DMX3cTSZn/uO0dSs5Oxk84p6y05KBmdj+B0pQlvHrTJtjiHwt1rhKIZLowfC89moexqwzVUWpOM7RZFlqUqmhxaU/ixNUWR8y4PxSdji/MYVddx1K7i13Th3qJw0q6i2QYva5MfFDZBxIDXIFr2gGjVC6LzK9CXxUN3bWVMSYOIeNGII4IRpFIERLsBgM24YH39NihV2kCp0BZK5XYQj/SSU+Ku2MWXIBOgNHsG+lWz8UN2NrTPFkOp7HRnLtTo6BOgJuSXIDFmRO1IRbsdaSgfY0ap5YQJUdtScdZh3Pdph4pHNhoTa94EobXhMROO2FAr3iKz5OmCSDi6PhJi9jEH7o42oVS0GWN/tckRF3+f+ZtduraA68krCpsgyMoxlsWZv+lM8pWSkgZ16lyPqQ9FkC7DnAtjOvT4TVBaPgulUlsoNTrJQNVT35cg2j/ehbZpj2GLs7KhzV8EUa194PXSxSQedNc751BRamUQxeUFnDyLNqH8agse2ZQitznSrXx/3lj9TVZ0tN9qTM17E+Ripor2W1Klm3K1VXaVGeud5XRRjddYUHq5CaVXmNAiPhmnbQbpoq9k4wGnVcoXCp0grpjBJUJAWxILpf0gKAxKXfWCEYQupsnTgDXVWDjl/MjZS9A3J0L95zzDmriCTT+C4IrJvelaX7oGSsNugddKVOsA9YulnvPqkHtXAxSXB5SKNuHdEw4cyVBxKUvD5SwVZxwqrNy0K7dn6uiwzciC9yZIUppA/fVeAXKsGRViLbicbdSjtdiXomCP1UBSipBujLLTqshg1/9a8ozCJog6aKIxS/nLEc9v7y2AUtNvGj0YQZiDwaD2mdegnzoPnZbIm2zpGRA9grsY9x5aXYM6eLwRrPpfK8G67Qf5bKecdMR209sny8SY8eXZTOPUzrjiHHfTZ2vIdsYhIQmSHkiQqmstsNK/eAW7wZCYKlCbwW+Qa8oTCp0gXYdDVO8I5Yl+0M9fNn5UFKivzTCm5V31QhFElnWCaN4L6v/Ohvrvr6HvPeR2V/qOJIjmPX0JogPaopXQmb/BP09fgOg+PPBanVCqREBP+s19bq7WNvB+UHnAk1tScD7TuDYGkn33pqH+RmM3fdw1Y5vEDRNklRmVV1tgdloeBqMTD9rkWwMMZEiMO2TDgH3pKFcUXYx7FMORxqAJgCPLcBenzkPtNMhTLxhB6GK4BE/IY5zxRuvnoW/ZI4+jy1E6vRJgQdSBE6C+/6Ukks745eAx5Dz4JJRgq8Rc6Pv7u26XJHQd8047UIJDTH8FXgfPJaZJs09j8e5xB0q5LFG0GQtOGzFIXghyf4wFB9ONBUTGIHU4R8M2gyHI9eQZvxtB2FMbdIP2XbSn9/+8FqKe84EFIwgtSP2uEE26QTTvDfHosxAtnoXoSJd12GjjyCmINi8GEoTD3CptocVucrslffs+iLq0WkHur0UfaJsT3fUpbx6xoXxsECXmgp6705DhHH+uuJyFOvEWVImzoNOmFBxONwgoCRIkSA1GEE6czT3lkISj1pZczEKztcmyzYrxFjkh13C1BdVWW1AyyPXkGb8nQaS/f7I/9ONnjUK6mhnzoFRtb5T5E6RSBNQeo4wg9eQ56LuSoO8+ICe83Md9sRRK3cAg1T1RVrMjtLVbnL/q0D5fDNGwe+B10zp1HQ79WrK7DcqPF7PQmslAy4wJqwCFyiGnSQ5H+Xej9VYcSDN6POPHQ+kC26yK3BAtnDFIqqKj07YbIwjRYoNVTuBR2EJyjobtVkUOyQ+kC5hydHx80iHJ5F83z7jlBKnYDtqS1e4m1Z6jPa5Brpx2MoauriFvZjbEiOkQVTtA7TLUXU/78GvZliBBOCnmL5oO7auf5OsYpEUgQabPdxczn0TO2vK8bV+EfuCoUeDIgjrtE+QwZ8Xv2plqKFr3hX7hqvdppGln/NAnMQ33UonLTHICi6OdOaczsepqjnyLEBVMonTdkSrnLbxlb4qCmUft8jtd0F93GC6m2loLdiUbBDmcIdAoIZAgfBFNI06WOY/zF17jR0WGIETdLhD1u0E06BY0s4vL63JyjMcQDY1lfxkfuH5jGzyesUujv0J9ZSq0dz6H9u5X0Jhb0vRv0vLI2MR93q6e+t7n5flooeo5yxr18AyP/a+Nn21ehL51n0/ykEv43GkZ+FBcHAjISY0xo/xKE57bm4YJR+3osDMVZVaa5TpMjVgLqsWaUcZ5LB9+pVgLqsfy05zr+0VIyrpxFgxKSsfEo3aMPWJD193pqL3Wkv+5GxcKhSC3ArQG1ToY6zN5SQO4CcjMt8Y9oE2ZBy1+h3t7QygJIIgLzCdZGcI15QckA9u9JW0XVYL8HqDlebgHRJsBhgVbsAT6yk3QVm2CHrfNnbsakiBFEWGC3ATkWlGkMapiXFSxHdQXxrkn48IECSMAxtZL5866MEHC8Ed4b24QpYThQdiCBFFKGB6ECRJEKWF4oA6c9Ifd3f/RqVAESU6F2vN1n5nPMIJDHTZdvnSYwqX8Nlv+OAT5ypnY5BIPQeyZUEcwoTdsQXJFnc5Qp813Lxcwkaf37rRAZRdBcCkhwWykJbjEQxBNhzp/sbH45a+UMNxQqkYYM6xe8tEJh0+qYJFEjBnNEqw478yddYmHIFxrOHne2JsSRDFhEJEQTw10vyPVJXQzVQsiYed3BNeBxh+yuTPfXOJDELk14PuVUGrd2vWOIonakVBaPQscOu6jMpcsZ+JwbBElSYwZrTZYcSwjcIHSlyAUbolc+HNg3mgxhlK3C5TG3aEzASmEME/o41MOlPNX/u2OlSY0ijcy1/yyFKQEEoTCTUn/jYdo9TyUBt2N5fFaUcZKJ5Xmn7rHwNYJhUv0TnB7gsw9LargvTXobqQA7P7VWOfPRUiSny5lo2FcMsrFOt8bcpuCuSuVVpvRd3eaTKwOJcEJQmGq3hUztMWxcg+L+vo7EK++Zbz7Y8xsiDHvQrxufDfeB/K2UT5yFsTImXJEpA6fATFsuhwWEmLoNKhDp7k/fcBjhk73HO9VJl4pZPD8o9+G+tYC6Ks2Gbv5blBIIb6e6rvzWRh30IYhe9PRPzEdL9wmeDExHSP2p2PaERvWmXMC/v2Hv4QmiEtIFCbPcO3Bwbf8OcGJIvnWPw90Zn/J75nQueEpCORrIIL97Xp7oLNuqOO8283tu3/9PIP3yz3A13mJXShhLUUzXkbDPNXbCcxquw4v3HJ9goSlWEuYILeBZGVlYe7cufj+++/9i9xit9vx4YcfYuHChf5Ft1SKDEEuXLiAQ4cO+f/sFiEEDhw4AJvN2F1fGLLWIjDjVDbOZOo46dAw/ng2Djgz0L1l7969iIqKwqOPPupGnz59sHnzZlluMplw//33o3Hjxv5V3cJjqlatiieeeMK/6JZKgREkOzsbK1asQKtWrVClShXUqlULQ4Z4tjLkRywWC7p3744777wT58+f9y+WsmPHDlSsWBH9+vXzL8q3LLoi0PNAFmac8p0gm3U6B7W22rEjVcVGq8B9G2xYZgqcS9iyZYvUR5kyZdC8eXM8/PDD8l5atGiBEydOQFVVSe5Tpzwv0vOXIk+QdevW4cEHH0SDBg0wceJEjB07FuPHj/c/7KaE5Fu8eDHeeustZGYG2QbB2cwrV/Dee+8hLi7OvyhfwhFgs50OPLjJhppb7eBShStuzStBSGBe/9WrV1GhQgVpNUjsnJwcxMbGYuNG4z9q8n737duH5cuXY9OmTdIq+hPk3LlziI6OxurVq+FwOJCRkSGPZZ39+/dD836bQj6kwAiyYMEC3H333ejVqxcURZEmnxftkjlz5sjePXDgQBw9auxT+eyzzySR6FcHDBiAmTNnYsyYMdLf8ga//vprDB06FL/88gvmzZsnLVJamrFxav369XjppZfw3HPP4aOPPsKZM2fwxhtv4Msvv8S1a9dkW5MmTcKPP/4oz0uyushFZQ8bNgz9+/fHqlWr5DliYmLc1+otG6wqym20oUdSliTD3Aue/Sk3SxCev2zZsnjooYeQlJSE1NRUaVUiIyMlOaZOnYo6derI46tXry5dkTdB2Marr76KSpUqyXs8fvw4evToIY9lHbZbUK62wAhCJdSsWRN33XWXJAn9Lh80iTJ69Gjcd9996NmzJ2rXri198NmzZ/H888/L42vUqIG6deti1KhRKFmypFQIHzL99gMPPICLFy/imWeeQYkSJXDp0iV88803sl61atXQpEkT+aD37NkjFcTvVBjPce+996Jp06aoXLmyrPv555/DarXK8/F6+FDYBstmzZrlf0tyu+Mbx7JRfqMdK8wq2iU60HynQ/77dUpeCcLroQ4Ya9CCTJs2TQaoKSkp8joef/xxJCcny+ulnr799lsZvNL9eBMkPj4ef/rTn9C5c2dJqK+++kreT+vWrbFkyRLZGaj7gpACIwj9KE0egy+aznLlymHKlCmy91MZDRs2lJbi5ZdfRvny5bFs2TJJECrtgw8+kCTYtm2bVAIJxZ7FB0l3xR7mIggDVcYjd9xxB3bt2iWtFZUXjCC8DrPZLC0Vj6d1WrRokfw+ePBgqcSlS5eGJMi5LA0RiQ603OWAQwOGHcmSZNmcYpDgZggSEREhHy5jNVfM4U2Q9PR0+aCpP+rSRWoXQRo1aiQJVr9+femGKHQzjPuIESNG4Oeff/a7gpuXAiOIS+gCaK75cOrVqyfNPxVCUjzyyCOyR7PX01eSIOwtjF8ormCUZvK7776TZphK9CbIzp07pQJZxp37LglGEFolCslYqlQpjBw5UsYptFKzZ8+WZadPnw5JkPhkgapb7Ki82Y6/7HZIMpTdYMPkk9lyIiyvBGFH4f3wvhmwjhs3LsCC8J6OHDkiOwY7CIny/vvvuwny2GOPSdCykhgUtsH4g26a5yDWrPH8b9/8SIERhBe4YcMGqfDExETpH0kQspk3zx7DB8dgkm6CMQYVRdYznnAJH1zp0qXRpk0bSRb6W2+CUHl0Yfz+008/yWCN8ceNEoTBLi1I79695QiCsUowgpB7E0/QvdgkOVy4f6MNUfscuJKj55kgrhjk2LFj8jsJQHfqTRB2MLoIumhaN452hg8f7uNi6HLYsXh/1CdHj7Q0Bw8elBaEdebP9+xVzo8UGEGoeFoNPiR+8gZmzJghI2xaEf7OEQ57f9++faV5D0YQPmj2mnvuuUcGpiSSN0EuX74sRyq0QrQiNLU0xTdKEFqpLl26yICadRncsd23337b624g8yIYb7RN9B019TpgBKtbUtSbJgiFcQPvkYEpO4yLILxXDoVpYVjOOIwjHW+CMO6YPHmydFnUy6effirJRmLwGAblHCkVhBQYQThi+fXXX6W7YK9g73Qpg3HCb7/9Ji0MwUkvmlJ+sjd5B1QManksRzr0xxTGN5z/OHz4sCwnaVh369atSEhIkGWunslYhsNGmnJeA4Xt0PKQXBSSZPv27dJdMSYhQfjAvIULt8ccmsxa95ZrOTp+s2vg++PMOTqO2zUZnzAR66hdQ5B5Mnl/JC2vzzX85DXyHvkbHzjLaQlZzvthGcFgnS6EsRQ7EnVDIZH4nfUYo/B+eY8nT550j/QKQgqMIEVJaLk4Evrkk0+kK/zzn/8sg+LbVdgpOGwNNQd0K6VYEoTB3JNPPilHFIMGDZLDRj6EsARKsSQI3SF9NP16Qc0X/FGlWBIkLDcuYYKEJVcJEyQsucr/A6H5PWR+y3SaAAAAAElFTkSuQmCC" 

    /** City shown in Location field on payslip */
    const val PAYSLIP_LOCATION_CITY = COMPANY_CITY


    // ══════════════════════════════════════════════════════════════════
    // 23. SPLASH SCREEN STATUS MESSAGES
    // ══════════════════════════════════════════════════════════════════

    const val SPLASH_MSG_CONNECTING = "Connecting\u2026"
    const val SPLASH_MSG_WAKING     = "Waking up server\u2026"
    const val SPLASH_MSG_ALMOST     = "Almost ready\u2026"
    const val SPLASH_MSG_LOADING    = "Loading your workspace..."
    const val SPLASH_MSG_STARTING   = "Starting up\u2026"


    // ══════════════════════════════════════════════════════════════════
    // 19. USER-FACING STRINGS (auto-use APP_NAME — don't hardcode)
    // ══════════════════════════════════════════════════════════════════

    val PERMISSION_LOCATION_RATIONALE get() =
        "$APP_NAME needs your location to:\n\n" +
        "• Record your punch-in/out location\n" +
        "• Verify you are within the office geofence\n" +
        "• Track field visits (OD)\n\n" +
        "Location is only recorded during work hours."

    val PERMISSION_BACKGROUND_SETTINGS_HINT get() =
        "To enable full tracking: Settings → Apps → $APP_NAME → Permissions → Location → Allow all the time"

    fun getBatteryOptSteps(brand: String): Pair<String, String> = when {
        brand.contains("xiaomi") || brand.contains("redmi") || brand.contains("poco") ->
            "📍 Enable AutoStart for Tracking" to
                "To ensure location tracking works when app is closed:\n\n" +
                "1. Open Phone Settings\n2. Go to Apps → $APP_NAME → Battery Saver\n" +
                "3. Select No restrictions\n4. Go back → AutoStart → Enable ✅\n\n" +
                "Without this, tracking stops after closing the app."
        brand.contains("oppo") || brand.contains("realme") ->
            "📍 Allow Background Activity" to
                "To ensure location tracking works when app is closed:\n\n" +
                "1. Open Phone Settings\n2. Go to Battery → App Battery Management\n" +
                "3. Find $APP_NAME → Allow background activity ✅\n\n" +
                "Without this, tracking stops after closing the app."
        brand.contains("oneplus") ->
            "📍 Disable Deep Optimization" to
                "To ensure location tracking works when app is closed:\n\n" +
                "1. Open Phone Settings\n2. Go to Battery → Battery Optimization\n" +
                "3. Find $APP_NAME → Don't optimize ✅\n\n" +
                "Without this, tracking stops after closing the app."
        brand.contains("vivo") ->
            "📍 Enable Background Location" to
                "To ensure location tracking works when app is closed:\n\n" +
                "1. Open iManager app\n2. Go to App Manager → $APP_NAME\n" +
                "3. Enable Background Power Consumption ✅\n\n" +
                "Without this, tracking stops after closing the app."
        brand.contains("huawei") || brand.contains("honor") ->
            "📍 Enable AutoLaunch" to
                "To ensure location tracking works when app is closed:\n\n" +
                "1. Open Phone Settings\n2. Go to Apps → $APP_NAME → Battery\n" +
                "3. Enable Auto Launch & Run in background ✅\n\n" +
                "Without this, tracking stops after closing the app."
        brand.contains("samsung") ->
            "📍 Remove Battery Restriction" to
                "To ensure location tracking works when app is closed:\n\n" +
                "1. Open Phone Settings\n2. Go to Apps → $APP_NAME → Battery\n" +
                "3. Select Unrestricted ✅\n\n" +
                "Without this, Samsung stops tracking after ~10 minutes."
        else ->
            "📍 Allow Background Location" to
                "To ensure location tracking works when app is closed:\n\n" +
                "1. Open Phone Settings\n2. Go to Apps → $APP_NAME → Battery\n" +
                "3. Select Unrestricted or No restrictions ✅\n\n" +
                "This ensures your attendance is tracked correctly."
    }
}
